### ISSUE TITLE
Add an argument to the control function for maximum workflow size

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#946] opened 2024-09-30 21:44 UTC
So that we can modulate these messages: 

> ℹ The workflow being saved contains a recipe, which is 20.78 Mb in memory. If this was not intentional, please set the control setting `save_workflow = FALSE`.

when `save_workflow = TRUE`.  The argument can be the Mb limit for giving this note. 

We can do the same for finetune too.

**Comment by simonpcouch** [comment] 2024-10-01 12:40
Related to #914.

**Comment by simonpcouch** [comment] 2024-10-01 12:41
Ah, duplicate of that issue—will close in favor of that one!

**Closed by simonpcouch** 2024-10-01 12:41 UTC
